name: Release Draft

on:

  workflow_call:
    inputs:
      name:
        type: string
        description: Release tag name
        required: true
      
jobs:

  create-release-draft:
    name: Create release draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Execute release draft creation
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ inputs.name }}
          draft: true
          prerelease: false
          tag_name: ${{ inputs.name }}
