name: Release Tag

on:

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Release version
        required: true

jobs:

  create-release-tag:
    name: Create release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Maven repository cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Set up Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: github.codeteapot
          
      - name: Execute release tag creation
        shell: bash
        run: |
          git config --global user.name codeteapot
          git config --global user.email codeteapot@gmail.com
          
          new_version="${{ github.event.inputs.version }}"
          mvn -B -f release-tag/pom.xml exec:exec@upgrade -DnewVersion=$new_version
          git push origin main
          git push origin v$new_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  create-release-draft:
    uses: codeteapot/javase-testing/.github/workflows/release-draft.yml@main
    permissions:
      contents: write
    with:
      name: "v${{ github.event.inputs.version }}"
  
